sudo: required

language: java
before_install:
  - mkdir ci-dependencies
  - cd ci-dependencies
  - curl -O https://openskywalking.github.io/skywalking-ci-assist/jars/ojdbc14-10.2.0.4.0.jar
  - curl -O https://openskywalking.github.io/skywalking-ci-assist/jars/resin-4.0.41.jar
  - cd ..

install:
  - jdk_switcher use oraclejdk8
  - travis_wait 30 mvn clean install -Ptravis-ci-submodule --quiet jacoco:report coveralls:report
  - travis_wait 30 mvn clean javadoc:javadoc -Dmaven.test.skip=true --quiet

